import Head from "next/head";
import React from "react";
import Sidebar from "../components/Sidebar";
import Trending from "../components/Trending";

const PostPage = () => {
	return (
		<div>
			<Head>
				<title>Twitter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="relative max-w-[1400px] mx-auto">
				<Sidebar />
				<div className="flex gap-6">
               <SinglePost />
					<Trending />
				</div>
			</main>
		</div>
	);
};

export default PostPage;
